// <auto-generated />
namespace Pharmacy_System.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Test2_alternation : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Test2_alternation));
        
        string IMigrationMetadata.Id
        {
            get { return "202005200614057_Test2_alternation"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
